COCO_KEYPOINTS = {
    "nose": 0,
    "left_eye": 1,
    "right_eye": 2,
    "left_ear": 3,
    "right_ear": 4,
    "left_shoulder": 5,
    "right_shoulder": 6,
    "left_elbow": 7,
    "right_elbow": 8,
    "left_wrist": 9,
    "right_wrist": 10,
    "left_hip": 11,
    "right_hip": 12,
    "left_knee": 13,
    "right_knee": 14,
    "left_ankle": 15,
    "right_ankle": 16,
}

HEAD_KEYPOINT_IDS = [0, 1, 2, 3, 4]
WRIST_KEYPOINT_IDS = [9, 10]

SHOULDER_KEYPOINT_IDS = [5, 6]

KEYPOINT_CONFIDENCE_THRESHOLD = 0.5
HEAD_KEYPOINT_CONFIDENCE_THRESHOLD = 0.5

DISTANCE_THRESHOLD_RATIO = 0.9
VERTICAL_OFFSET_RATIO = 0.2
CONFIRMATION_FRAMES = 30
MAX_GAP_FRAMES = 10
MIN_EVENT_FRAMES = 30

HEAD_TURN_THRESHOLD_RATIO = 0.25
HEAD_TURN_WINDOW_FRAMES = 90
HEAD_TURN_MAX_TURNS = 3

HEAD_TURN_AWAY_MIN_FACE_VISIBLE_FRAMES = 3
HEAD_TURN_AWAY_MIN_FACE_HIDDEN_FRAMES = 5
HEAD_TURN_AWAY_NOSE_CONFIDENCE_THRESHOLD = 0.2
HEAD_TURN_AWAY_BODY_CONFIDENCE_THRESHOLD = 0.4
HEAD_TURN_AWAY_BODY_MIN_VISIBLE_KEYPOINTS = 2
HEAD_TURN_AWAY_WINDOW_FRAMES = 90
HEAD_TURN_AWAY_MAX_TURNS = 3

SMOOTHING_MIN_PADDING = 40

HAND_SHAKE_OBJECT_WINDOW_FRAMES = 40
HAND_SHAKE_OBJECT_MIN_REVERSALS = 3
HAND_SHAKE_OBJECT_MIN_DISPLACEMENT_RATIO = 0.01

HAND_SNATCH_OBJECT_MIN_GRASP_FRAMES = 3
HAND_SNATCH_OBJECT_VELOCITY_RATIO = 0.15
HAND_SNATCH_OBJECT_APPROACH_WINDOW = 10
HAND_SNATCH_OBJECT_BASELINE_RATIO = 2.0
HAND_SNATCH_OBJECT_KEYPOINT_CONF_THRESHOLD = 0.5

BODY_TURN_MIN_ANGLE = 45.0
BODY_TURN_WINDOW_FRAMES = 15
BODY_TURN_VELOCITY_THRESHOLD = 10.0
BODY_TURN_CONFIDENCE_FRAMES = 30
BODY_TURN_MAX_GAP_FRAMES = 10
BODY_TURN_MIN_EVENT_FRAMES = 30

# --- Keypoint classifier (one model per behavior) ---
CLASSIFIER_DEFAULT_THRESHOLD = 0.5
CLASSIFIER_MIN_SEQUENCE_FRAMES = 3
CLASSIFIER_MIN_TRACK_QUALITY = 0.5
CLASSIFIER_MIN_DURATION_SEC = 0.5
CLASSIFIER_TARGET_LEN = 32
CLASSIFIER_DEFAULT_MODE = "temporal"
